### ISSUE TITLE
Override keybindings

### ISSUE THREAD

**Issue by ArciAndres** [sasza2/react-panzoom#109]
Hi! It's me again :).

I was wondering what would be the best option to have different control keys for the PanZoom area.
Currently, it is implemented in this way:

**ZOOM:** Mouse scroll
**PAN:** Click + movement of mouse

I would like to have the following behavior:

**ZOOM:** (CTRL or CMD) + Mouse scroll
**PAN (vertical):** Mouse scroll
**PAN (horizontal):** SHIFT + Mouse scroll

I guess I could reach a similar behavior implementing my own keybindings and using PanZoomRef, but I would not like to conflict with the current bindings. 
What could be done to reach this interaction?

Thank you in advance! Awesome library ❤️.

**Comment by sasza2** [comment]
thanks. ok, I already have hook that allows to scroll vertically because I needed it too. I will add it to library in next days when I figure out how to name new properties

**Comment by ArciAndres** [comment]
Thanks you very much! Keep me in the loop :)

**Comment by sasza2** [comment]
please check version 1.9.0 and file: https://github.com/sasza2/react-panzoom/blob/develop/src/stories/Scroll.stories.tsx

**Comment by ArciAndres** [comment]
I tested it and it works awesome man! 
Thank you so much! I'm sure this feature will be useful for other people as well.
