### ISSUE TITLE
No issues just wanted to express deep love toward library creator

### ISSUE THREAD

**Issue by yevgeniusr** [sasza2/react-panzoom#48]
Bro thanks for mobile zooming, you saved my ass lol

**Comment by yevgeniusr** [comment]
Let's connect on LinkedIn https://www.linkedin.com/in/yev-rachkovan/

**Comment by yevgeniusr** [comment]
Do you know by a chance how can I add some kind of smooth animations for pinching and zooming and dragging elements?

**Comment by sasza2** [comment]
hehe, you're welcome! hmm, you want to animate content inside of elements when user is pinching/zooming/dragging?

**Comment by yevgeniusr** [comment]
> hehe, you're welcome! hmm, you want to animate content inside of elements when user is pinching/zooming/dragging?

I wanna have inertia when users are changing positions. You know when you scroll on mac, you can kinda push the scroll and then there is an inertia that slowly pushes you forward. Miro and other collaboration apps have it. If you have in mind how to change it from the library side let me know, would be happy to contribute

**Comment by sasza2** [comment]
could you post here some video/gif example of that animation from miro/any other app? it should be easier to understand. thanks!
