### ISSUE TITLE
Help - how to migrate to react-panzoom

### ISSUE THREAD

**Issue by HighLiuk** [sasza2/react-panzoom#51]
Hello, I'm very glad to know about this package. So first of all, thank you @sasza2 for all the efforts you put in this project.
I'd like to migrate my project to your library, and I need to know how to reproduce something like this: https://codesandbox.io/s/eager-frost-9pgqnv?file=/index.html

Notice how:

- I can pan the background image, which covers the container
- I cannot pan or zoom outisde the background image, though I can zoom in
- the two balloons inside follow the background as if they were stick to it, though they can be freely moved around the background, but they cannot move out of it

I tried a couple hours with this library but I couldn't manage to reproduce it, especially for the first two points. Can you help me reproduce it?

Thanks in advance 🙏🏻

**Comment by sasza2** [comment]
hello,

do you mean something like that https://codesandbox.io/s/sweet-mclaren-ygc0sl?file=/src/index.js ?

**Comment by HighLiuk** [comment]
Hello @sasza2 and thank you for the fast response.

Yet not close enough, for the following reasons:

1.  If I click on the background, the whole background image should move, together with the balloons. In doing so, the image should be constrained to **cover** its container
2.  The background image should zoom when zooming is triggered (e.g. on mouse wheel)
3.  The balloons should be constrained to **contain** the container (can't go out of it)

If I'm not clear enough, please try out the code sandbox I posted.

Is it possible to achieve this with the current version?

**Comment by sasza2** [comment]
ok, it's quick change. try this one https://codesandbox.io/s/youthful-lucy-i66z9p?file=/src/index.js

**Comment by HighLiuk** [comment]
@sasza2 thanks, but not yet what I need.

Something more like this one > https://codesandbox.io/s/determined-danilo-l5il0s?file=/src/index.js
but with a few questions:

- how to prevent page scrolling when zooming with mouse wheel?
- how to prevent the default panning behaviour of the `Element` component when I click on it? Precisely, I need to preserve the normal resizing behaviour of the elements via CSS `resize: both; overflow: auto`

**Comment by sasza2** [comment]
ok, i just added zoomMin and boundary props to example above

`first question:`
it should already working, there's event.preventDefault() on zoom wheel

`second question:`
if you click on element you can receive callback onClick at `<Element ... onClick={onElementClick} />`
with argument https://github.com/sasza2/react-panzoom/blob/master/types/types.ts#L94-L99
just call `stop()` function

**Comment by HighLiuk** [comment]
Very nice thank you.
What about setting an initial zoom? I need the image to zoom out as much as possible still fitting the container on the initial page load

**Comment by sasza2** [comment]
oh, I need to add that as a new feature hehe. should be easy

**Comment by HighLiuk** [comment]
Oh, if that is the case, I already have an idea of how to implement it. May I open a PR in the next few days?

**Comment by sasza2** [comment]
yes, sure

**Comment by HighLiuk** [comment]
Thanks @sasza2 for all of your effort, I really appreciate it. Will you link here a reference to your PR when it will be ready to be merged into master branch? I'm talking of [feature/pan-zoom-with-cover](https://github.com/sasza2/react-panzoom/compare/feature/pan-zoom-with-cover). That would be helpful for future readers.

**Comment by sasza2** [comment]
I just published new version 1.6.2 by merging this PR https://github.com/sasza2/react-panzoom/pull/58 and I also added  you as a collaborator in package.json (hope it's okay with you)

**Comment by HighLiuk** [comment]
@sasza2 I'm honoured 🙏🏻 thanks

**Comment by HighLiuk** [comment]
@sasza2 Happy new year! 🥳🎆🎇

**Comment by sasza2** [comment]
thanks @HighLiuk! Happy New Year!
I have a gift for you https://github.com/sasza2/panzoom-core almost ready hehe
