### ISSUE TITLE
Weird offset appears while panning far away from the container

### ISSUE THREAD

**Issue by HighLiuk** [sasza2/react-panzoom#59]
Hello again @sasza2,

I have seen this weird bug in most of your demos and stories

![Screen Capture on 2022-11-28 at 23-29-13](https://user-images.githubusercontent.com/65017775/204394689-c0dfcdbd-6004-40ba-b144-b9f3215b4b2a.gif)

can you confirm this is a bug?

Here is the code to reproduce it:

```js
import PanZoom, { Element } from '@sasza/react-panzoom';

const App = () => {
  return (
    <div
      style={{
        width: 400,
        height: 400,
        background: '#bbb',
      }}
    >
      <style
        dangerouslySetInnerHTML={{
          __html: `
            .react-panzoom__in {
              background: #555
            }
          `,
        }}
      ></style>

      <PanZoom boundary={{}}>
        <Element id="red" x={100} y={100}>
          <div
            style={{
              width: 100,
              height: 100,
              background: '#999',
            }}
          ></div>
        </Element>
      </PanZoom>
    </div>
  );
};

export default App;

```

**Comment by sasza2** [comment]
yes, it's a bug. it should be fixed here https://github.com/sasza2/react-panzoom/blob/master/src/helpers/appendToCurrentPosition.ts#L63-L66

sometimes `toAdd.x` / `toAdd.y` with current positionRef goes beyond boundary.
it's easy for left and top edge because it should do the job:

```
if (positionRef.current.x > 0) positionRef.current.x = 0
if (positionRef.current.y > 0) positionRef.current.y = 0
```

but I must think about right and bottom edge to also make it clean and simple.
for now I think that all the needed code is in `isEdgeVisible.ts` file and I just need to create some helper.

thanks for reporting

**Comment by HighLiuk** [comment]
I'd like to help you debug that.
I really like the API that this package exposes and I look forward to use it in my projects!
I'll try tracking the bug down in the next days 🪲

**Comment by sasza2** [comment]
sorry, I probably just fixed it right now here https://github.com/sasza2/react-panzoom/tree/bugfix/extra-offset-while-panning-on-zoomout hehe. could you check in free time if issue still exist?

**Comment by HighLiuk** [comment]
Hey @sasza2 haha that's not even a challenge if you have the solution even before I post a comment 😂
Just kidding, by the way I've just tried your branch and the issue seems fixed! Thanks a lot!

**Comment by sasza2** [comment]
haha, thanks for checking!
