### ISSUE TITLE
First zoom around point not working when using boundary prop

### ISSUE THREAD

**Issue by HighLiuk** [sasza2/react-panzoom#61]
Hello @sasza2,

I hope you do not hate me for submitting two issues for a bug in a row 😂
It's just that I look forward to use this library in my projects because I really love the API it exposes.

In the following you can see how when I zoom in or out around a point, it does not always zoom around *that* point.

![Screen Capture on 2022-11-30 at 22-53-49](https://user-images.githubusercontent.com/65017775/204916411-7e812ee7-c892-4ca3-be25-6e5c416a7b9c.gif)

Here a few more things I noticed that may help you debug that:

- if I zoom a couple times, it's just the first zoom that is "wrong": the rest of them zoom correctly
- but if I then reverse the zoom, the bug shows up again. For instance, if I zoom in twice and then I zoom out twice, the first and third zooms are bugged, while the second and the fourth are not
- this bug appears in the stories "Box Bounding", "Puzzle" and "Cover", which all use the boundary prop, while the bug does not appear in the "Rectangles" story, which does not use it

P.S. I saw this bug on 1.15, too (as far as I remember)

**Comment by HighLiuk** [comment]
Great @sasza2, this is fixed now. Thanks

**Comment by sasza2** [comment]
you're welcome. thank you too!
