### ISSUE TITLE
Element disabled attribute is too restrictive

### ISSUE THREAD

**Issue by HighLiuk** [sasza2/react-panzoom#76]
Hey @sasza2, I'm using React Panzoom on a project, but I've noticed that the `disabled` attribute on the `Elements` component is too restrictive since it:

- disables panning the element
- disables `onClick`
- disables `onMouseUp`
- adds potentially unwanted CSS styles

The CSS stuff is fixed by something like

```html
<Element className="remove-styles" />
```

```css
.remove-styles {
  pointer-events: auto !important;
  /* cursor: pointer; */
}
```

but it's not ideal to force the developer to use `!important` in their stylesheets.

For the interactive part, the only way I've managed to make it interactive is by moving the `onClick` / `onMouseUp` handlers in the `Element` children. But I'm not sure if this is the intended way of using it.

What do you think about it?

**Comment by sasza2** [comment]
@HighLiuk so you want to remove `pointer-events` when disabled is true?

**Comment by HighLiuk** [comment]
I think that the library should only add necessary CSS in order for it to work correctly, otherwise the dev should first override them (and not with specificity since it's an inline style, unless it's a class with !important), then apply their own

**Comment by HighLiuk** [comment]
By the way I've also found a case in which I need to add overflow hidden on the container element otherwise it's bugged (I guess). But maybe I'm just doing something the wrong way...

**Comment by sasza2** [comment]
```I think that the library should only add necessary CSS in order for it to work correctly, otherwise the dev should first override them (and not with specificity since it's an inline style, unless it's a class with !important), then apply their own```

I guess you want to click on someting in Element when its disabled, right?

```

By the way I've also found a case in which I need to add overflow hidden on the container element otherwise it's bugged (I guess). But maybe I'm just doing something the wrong way...
```
You could always create new issue, I'm curious hehe

**Comment by HighLiuk** [comment]
> I guess you want to click on someting in Element when its disabled, right?

yeah sure. Also, I want the cursor pointer but that does not appear when pointer events is none.

That's a scenario in which I want the elements to zoom according to the background, they should be fixed (unmovable) though, and they should react to click events (though I can add onClick to their child)

**Comment by sasza2** [comment]
Ok, seems obvious. could you please delete this line https://github.com/sasza2/react-panzoom/blob/develop/src/styles.ts#L39 in new PR? It should fix your issue. I will merge it

**Comment by HighLiuk** [comment]
> You could always create new issue, I'm curious hehe

solved. I was using a div with styles wrapping the panzoom element, but I should have used only the panzoom element with classname.

> could you please delete this line?

Sure, I'll do that later though. Thanks. I leave the issue open as a reminder.

**Comment by sasza2** [comment]
`solved. I was using a div with styles wrapping the panzoom element, but I should have used only the panzoom element with classname.`

If there is something misleading in lib behaviour, maybe we could add something about it to README.md

`Sure, I'll do that later though. Thanks. I leave the issue open as a reminder.`

ok, ok. thank you too!
